# SPDX-License-Identifier: MIT
"""Public package interface for ``iontrap_dynamics``."""

from .cache import (
    CACHE_FORMAT_VERSION,
    compute_request_hash,
    load_trajectory,
    save_trajectory,
)
from .conventions import CONVENTION_VERSION, FOCK_CONVERGENCE_TOLERANCE
from .entanglement import (
    concurrence_trajectory,
    entanglement_of_formation_trajectory,
    log_negativity_trajectory,
)
from .exceptions import (
    BackendError,
    ConventionError,
    ConvergenceError,
    FockConvergenceWarning,
    FockQualityWarning,
    IntegrityError,
    IonTrapError,
    IonTrapWarning,
)
from .measurement import (
    BernoulliChannel,
    BinomialChannel,
    BinomialSummary,
    DetectorConfig,
    ParityScan,
    PoissonChannel,
    SidebandInference,
    SpinReadout,
    binomial_summary,
    clopper_pearson_interval,
    sample_outcome,
    wilson_interval,
)
from .results import (
    MeasurementResult,
    Result,
    ResultMetadata,
    ResultWarning,
    StorageMode,
    TrajectoryResult,
    WarningSeverity,
)
from .systematics import (
    DetuningDrift,
    DetuningJitter,
    PhaseDrift,
    PhaseJitter,
    RabiDrift,
    RabiJitter,
    apply_detuning_drift,
    apply_phase_drift,
    apply_rabi_drift,
    perturb_carrier_rabi,
    perturb_detuning,
    perturb_phase,
)

__all__ = [
    "CACHE_FORMAT_VERSION",
    "CONVENTION_VERSION",
    "FOCK_CONVERGENCE_TOLERANCE",
    "BackendError",
    "BernoulliChannel",
    "BinomialChannel",
    "BinomialSummary",
    "ConventionError",
    "ConvergenceError",
    "DetectorConfig",
    "DetuningDrift",
    "DetuningJitter",
    "FockConvergenceWarning",
    "FockQualityWarning",
    "IntegrityError",
    "IonTrapError",
    "IonTrapWarning",
    "MeasurementResult",
    "ParityScan",
    "PhaseDrift",
    "PhaseJitter",
    "PoissonChannel",
    "RabiDrift",
    "RabiJitter",
    "Result",
    "ResultMetadata",
    "ResultWarning",
    "SidebandInference",
    "SpinReadout",
    "StorageMode",
    "TrajectoryResult",
    "WarningSeverity",
    "apply_detuning_drift",
    "apply_phase_drift",
    "apply_rabi_drift",
    "binomial_summary",
    "clopper_pearson_interval",
    "compute_request_hash",
    "concurrence_trajectory",
    "entanglement_of_formation_trajectory",
    "load_trajectory",
    "log_negativity_trajectory",
    "perturb_carrier_rabi",
    "perturb_detuning",
    "perturb_phase",
    "sample_outcome",
    "save_trajectory",
    "wilson_interval",
]
